name: Neon Preview DB & Schema Diff

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get current branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

      - name: Create Neon preview branch
        id: neon
        if: github.event.action != 'closed'
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}-${{ steps.branch_name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci

      - name: Run Drizzle migrations on preview DB
        if: github.event.action != 'closed'
        run: npx drizzle-kit push --config drizzle.config.json
        env:
          DATABASE_URL: ${{ steps.neon.outputs.db_url_with_pooler }}

      - name: Post schema diff comment
        if: github.event.action != 'closed'
        uses: neondatabase/schema-diff-action@v1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          compare_branch: preview/pr-${{ github.event.number }}-${{ steps.branch_name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Delete Neon preview branch
        if: github.event.action == 'closed'
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}-${{ steps.branch_name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
